### ISSUE TITLE
Segfault with app init

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#326]
Get a segfault when trying to use custom path for dockerfile
```
~/workspace/aws-reinvent-2018-trivia-game(master)$ archer app init
Note: It's best to run this command in the root of your workspace.
? Which type of infrastructure pattern best represents your application? Load Balanced Web App
? What do you want to call this Load Balanced Web App? goose
? Which Dockerfile would you like to use for goose app? Enter a custom path
? OK, what's the path to your Dockerfile? ./

✔ Success! Wrote the manifest for goose app at 'ecs-project/goose-app.yml'
Your manifest contains configurations like your container size and ports.

⠼ Creating ECR repositories for application goose. panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x16008f1]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli-v2/internal/pkg/deploy/cloudformation.CloudFormation.getLastDeployedProjectConfig(0x1c032a0, 0xc000362540, 0x1c31ba0, 0xc0000ac0c8, 0x1c1e400, 0xc00023a1b0, 0xc000133aa0, 0x203000, 0x8, 0xc0001339b8)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/deploy/cloudformation/project.go:338 +0x121
github.com/aws/amazon-ecs-cli-v2/internal/pkg/deploy/cloudformation.CloudFormation.AddAppToProject(0x1c032a0, 0xc000362540, 0x1c31ba0, 0xc0000ac0c8, 0x1c1e400, 0xc00023a1b0, 0xc000020120, 0xc0000b7e10, 0x5, 0xc00032a140, ...)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/deploy/cloudformation/project.go:142 +0xff
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.(*InitAppOpts).Execute(0xc0002d60c0, 0x0, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/app_init.go:121 +0x60c
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.BuildAppInitCmd.func2(0xc000302500, 0x21ea120, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/app_init.go:334 +0xc6
github.com/spf13/cobra.(*Command).execute(0xc000302500, 0x21ea120, 0x0, 0x0, 0xc000302500, 0x21ea120)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00024d400, 0x0, 0x0, 0xc000098058)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/hsinghui/workspace/amazon-ecs-archer/cmd/archer/main.go:25 +0x27

```

**Comment by efekarakus** [comment]
False alarm :)
